[package]
name = "elenar2"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
reqwest = "0.13.1"
serde_json = "1.0.149"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tui-scrollview = "0.6.2"
